### ISSUE TITLE
Register nick and perform ident at login

### ISSUE THREAD

**Issue by Sunii** [TeamPeggle/ppp-helpdesk#7]
Register nick and perform ident at login so bot can be auto op'd

https://github.com/TeamPeggle/ppp-helpdesk/blob/ppp-helpdesk/docs/Configuration.md

**Comment by ParkerM** [comment]
Added [this pull request](https://github.com/TeamPeggle/ppp-helpdesk/pull/8) that would let us load the config from a private remote repo. Example repo here: https://github.com/ParkerM/ppp-helpdesk-config

This would let us store the nickserv info and allow any repo members to update it if needed.

**Comment by imnotjames** [comment]
It does this now
